from reportlab.lib import colors
from app.pdf_layout.style import (
    PRIMARY_BLUE,
    TEXT_DARK,
    PAGE_MARGIN_LEFT,
    PAGE_MARGIN_RIGHT,
)

# ⭐ NEW: Subtle divider line helper for premium section separation
def draw_divider(c, y, color="#CCCCCC"):
    c.setStrokeColor(colors.HexColor(color))
    c.setLineWidth(0.5)
    c.line(PAGE_MARGIN_LEFT - 10, y, PAGE_MARGIN_RIGHT + 10, y)


def draw_header_footer(c, page_number, report_title="OptimaAI Underwriting Report", report_date="Feb 19, 2026"):
    """
    Premium header/footer with safe vertical positioning.
    Header lowered to avoid clipping AND avoid overlapping content.
    """

    # --- HEADER BAR (safe zone: 740–770) ---
    HEADER_Y = 740
    HEADER_HEIGHT = 30

    # Blue header bar
    c.setFillColor(PRIMARY_BLUE)
    c.rect(
        PAGE_MARGIN_LEFT - 10,
        HEADER_Y,
        (PAGE_MARGIN_RIGHT - PAGE_MARGIN_LEFT) + 20,
        HEADER_HEIGHT,
        fill=1,
        stroke=0,
    )

    # Header text
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(PAGE_MARGIN_LEFT, HEADER_Y + 10, report_title)

    c.setFont("Helvetica", 10)
    c.drawRightString(PAGE_MARGIN_RIGHT, HEADER_Y + 10, report_date)

    # --- FOOTER LINE ---
    c.setStrokeColor(colors.HexColor("#CCCCCC"))
    c.setLineWidth(0.5)
    c.line(PAGE_MARGIN_LEFT - 10, 50, PAGE_MARGIN_RIGHT + 10, 50)

    # --- FOOTER TEXT ---
    c.setFillColor(TEXT_DARK)
    c.setFont("Helvetica", 9)
    c.drawString(PAGE_MARGIN_LEFT, 36, "Generated by OptimaAI")
    c.drawRightString(PAGE_MARGIN_RIGHT, 36, f"Page {page_number}")
